ui <- dashboardPage(
  dashboardHeader(title="Proteomics Data Analysis Pipeline"),
  dashboardSidebar(
    h4("File input"),
    fileInput("raw_data", "please upload .csv/.xlsx file of raw data with quantitative intensities of proteins:",
              multiple = FALSE,
              accept = c("text/csv",
                         "text/comma-separated-values,text/plain",
                         ".csv", ".xlsx")),
    fileInput("meta_data", "please upload .csv/.xlsx file of meta data with only sample names matched with raw data, and corresponding covariates of interest:",
              multiple = FALSE,
              accept = c("text/csv",
                         "text/comma-separated-values,text/plain",
                         ".csv", ".xlsx")),
    h4("1. Graphs at QC stage"),
    #QC Plots
    selectizeInput("options", 
                   label="Quality Control graph options", 
                   choices = c( "%CV plots for QC samples",
                                "%CV plots for QC samples stacked bar",
                                "Distribution of identified proteins",
                                "Overlap of identified proteins",
                                "Data Completeness")),
    conditionalPanel('(input.options == "Distribution of identified proteins")|(input.options == "Overlap of identified proteins")',
                     uiOutput("group")),
    # Normalization, imputation, etc.
    h4("2. Processing"),
    numericInput("filterlevel", 
                 h5("Row filter level (%)"), 
                 value = 0),
    checkboxInput(inputId = "normalization", 
                  "Median Normalization", value = FALSE),
    checkboxInput(inputId = "whetherimpute", 
                  "Imputation", value = FALSE),
    conditionalPanel(condition='input.whetherimpute==1',
                     selectInput(inputId = "imputation", 
                                 label="Imputation Method", 
                                 choices = c( "Down-shifted Normal samples",
                                              "MinProb",
                                              "knn",
                                              "min"),
                                 selected = NULL)),
    # tests
    h4("3. Inference on Differential Expression"),
    checkboxInput(inputId = "whetherblock", 
                  "Blocking", value = FALSE),
    conditionalPanel('input.whetherblock==1',
                     uiOutput("blockfactor")),
    selectInput(inputId = "DEtest", 
                label="Statistical testing for DE", 
                choices = c("limma",
                            "t-test"),
                selected = NULL),
    uiOutput("FoI"),
    
    # Dimensionality Reduction
    h4("4. Dimensionality reduction"),
    selectInput(inputId = "DRmethod", 
                label="use the method of...",
                choices=c("PCA","t-SNE", "UMAP")),
    uiOutput("colorfactor"),
    
    # clustering
    h4("5. Clustering"),
    selectInput(inputId = "Cmethod", 
                label="use the method of...",
                choices=c("Hierarchical Clustering",
                          "Fuzzy Clustering")),
    selectInput(inputId = "rows", 
                label="use the rows of...",
                choices=c("significant","all")),
    conditionalPanel('input.Cmethod == "Hierarchical Clustering"',
                     checkboxInput("whetherlabel", 
                                   h5("include row labels"), 
                                   value = FALSE)),
    conditionalPanel('input.Cmethod != "Hierarchical Clustering"',
                     numericInput("clusternum", 
                                  h5("the number of centers: "), 
                                  value = 2))
  ),
  dashboardBody(
    fluidRow(tabBox(title = "Input & Pre-processing",
                    tabPanel("Graphs at QC stage",
                             plotOutput("graph")),
                    tabPanel("Head", 
                             h5("The first 5 rows and 5 columns of data currently"),
                             tableOutput("view")))
    ),
    fluidRow(tabBox(title="DE test and others",
                    tabPanel("Volcano plot",
                             h5("Volcano plot of DE testing results"),
                             plotOutput("volcanoplot")),
                    tabPanel("Dimensionality Reduction",
                             h5("Output of dimensionality reduction methods"),
                             plotOutput("dimenreduction")),
                    tabPanel("Clustering",
                             h5("Output of clustering"),
                             plotOutput("cluster"))
    )
    )
  )
)